package com.eudhari.view.admin;

import com.eudhari.controller.AdminController;
import com.eudhari.model.ReportModel;
import javafx.beans.property.SimpleStringProperty;
import javafx.collections.FXCollections;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.chart.*;
import javafx.scene.control.*;
import javafx.scene.layout.*;

public class AnalysisView {
    private final AdminController controller;
    private final Runnable onBack;
    private final ScrollPane rootPane;

    // Styling constants
    private static final String FONT = "-fx-font-family: 'Segoe UI', sans-serif;";
    private static final String APP_BG = "#c1e1ff";
    private static final String CARD_BG = "#FFFFFF";
    private static final String BORDER_COLOR = "#E2E8F0";
    private static final String PRIMARY_COLOR = "#3A57E8";

    public AnalysisView(AdminController controller, Runnable onBack) {
        this.controller = controller;
        this.onBack = onBack;
        this.rootPane = buildView();
    }

    public Node getView() {
        return rootPane;
    }

    private ScrollPane buildView() {
        VBox mainContent = new VBox(24);
        mainContent.setPadding(new Insets(24, 32, 32, 32));
        mainContent.setStyle("-fx-background-color: " + APP_BG + ";");

        // Header
        HBox headerRow = new HBox(14);
        headerRow.setAlignment(Pos.CENTER_LEFT);

        if (onBack != null) {
            Button backBtn = createBackButton(onBack);
            headerRow.getChildren().add(backBtn);
        }

        VBox titleBox = new VBox(4);
        Label title = new Label("Reports & Analytics");
        title.setStyle(FONT + "-fx-font-size: 20px; -fx-font-weight: bold; -fx-text-fill: #0F172A;");
        Label subtitle = new Label("Platform performance, growth metrics, and audit logs.");
        subtitle.setStyle(FONT + "-fx-font-size: 12px; -fx-text-fill: #64748B;");
        titleBox.getChildren().addAll(title, subtitle);

        Region spacer = new Region();
        HBox.setHgrow(spacer, Priority.ALWAYS);

        ComboBox<String> timeRange = new ComboBox<>(
                FXCollections.observableArrayList("Last 7 Days", "Last 30 Days", "Last 6 Months", "This Year"));
        timeRange.setValue("Last 7 Days");
        timeRange.setStyle(FONT
                + "-fx-background-color: #FFFFFF; -fx-background-radius: 8px; -fx-border-color: #CBD5E1; -fx-border-radius: 8px; -fx-padding: 4px 10px; -fx-font-size: 12px;");

        Button exportBtn = createSecondaryButton("⬇ Export");
        exportBtn.setOnAction(e -> {
            Alert alert = new Alert(Alert.AlertType.INFORMATION, "Exporting analytics report as CSV/PDF...",
                    ButtonType.OK);
            alert.showAndWait();
        });

        HBox actions = new HBox(10, timeRange, exportBtn);
        actions.setAlignment(Pos.CENTER_RIGHT);

        headerRow.getChildren().addAll(titleBox, spacer, actions);
        mainContent.getChildren().add(headerRow);



        // Bottom Section: Reports Table Card
        VBox reportsCard = createCard();
        HBox repHeader = new HBox();
        repHeader.setAlignment(Pos.CENTER_LEFT);
        Label repSectionTitle = new Label("Audit & Analytical Reports");
        repSectionTitle.setStyle(FONT + "-fx-font-size: 15px; -fx-font-weight: bold; -fx-text-fill: #0F172A;");
        repHeader.getChildren().add(repSectionTitle);

        TableView<ReportModel> repTable = new TableView<>();
        styleTableView(repTable);
        repTable.setPrefHeight(240);

        TableColumn<ReportModel, String> colId = new TableColumn<>("REPORT ID");
        colId.setCellValueFactory(d -> new SimpleStringProperty(d.getValue().getReportId()));
        colId.setPrefWidth(110);

        TableColumn<ReportModel, String> colType = new TableColumn<>("REPORT TYPE");
        colType.setCellValueFactory(d -> new SimpleStringProperty(d.getValue().getReportType()));
        colType.setPrefWidth(220);

        TableColumn<ReportModel, String> colDate = new TableColumn<>("GENERATED DATE");
        colDate.setCellValueFactory(d -> new SimpleStringProperty(d.getValue().getGeneratedDate()));
        colDate.setPrefWidth(140);

        TableColumn<ReportModel, String> colBy = new TableColumn<>("GENERATED BY");
        colBy.setCellValueFactory(d -> new SimpleStringProperty(d.getValue().getGeneratedBy()));
        colBy.setPrefWidth(130);

        TableColumn<ReportModel, String> colStatus = new TableColumn<>("STATUS");
        colStatus.setCellValueFactory(d -> new SimpleStringProperty(d.getValue().getStatus()));
        colStatus.setCellFactory(col -> new TableCell<ReportModel, String>() {
            @Override
            protected void updateItem(String item, boolean empty) {
                super.updateItem(item, empty);
                if (empty || item == null) {
                    setGraphic(null);
                } else {
                    setGraphic(createBadge(item));
                }
            }
        });
        colStatus.setPrefWidth(100);

        TableColumn<ReportModel, String> colSize = new TableColumn<>("FILE SIZE");
        colSize.setCellValueFactory(d -> new SimpleStringProperty(d.getValue().getFileSize()));
        colSize.setPrefWidth(100);

        TableColumn<ReportModel, Void> colAction = new TableColumn<>("ACTION");
        colAction.setCellFactory(col -> new TableCell<ReportModel, Void>() {
            private final Button dlBtn = new Button("Download");
            {
                dlBtn.setStyle(FONT
                        + "-fx-background-color: #EEF2FF; -fx-text-fill: #3A57E8; -fx-font-size: 11px; -fx-font-weight: bold; -fx-background-radius: 6px; -fx-padding: 4px 10px; -fx-cursor: hand;");
                dlBtn.setOnAction(e -> {
                    ReportModel r = getTableView().getItems().get(getIndex());
                    Alert a = new Alert(Alert.AlertType.INFORMATION,
                            "Downloading " + r.getReportType() + " (" + r.getFileSize() + ")...", ButtonType.OK);
                    a.showAndWait();
                });
            }

            @Override
            protected void updateItem(Void item, boolean empty) {
                super.updateItem(item, empty);
                setGraphic(empty ? null : dlBtn);
            }
        });
        colAction.setPrefWidth(120);

        repTable.getColumns().addAll(colId, colType, colDate, colBy, colStatus, colSize, colAction);
        repTable.setItems(controller.getAllReports());

        reportsCard.getChildren().addAll(repHeader, new Region() {
            {
                setPrefHeight(8);
            }
        }, repTable);
        mainContent.getChildren().add(reportsCard);

        ScrollPane sp = new ScrollPane(mainContent);
        sp.setFitToWidth(true);
        sp.setStyle(
                "-fx-background-color: transparent; -fx-background: " + APP_BG + "; -fx-border-color: transparent;");
        return sp;
    }

    private VBox createCard(Node... children) {
        VBox card = new VBox(children);
        card.setStyle("-fx-background-color: " + CARD_BG + "; -fx-background-radius: 12px; " +
                "-fx-border-color: " + BORDER_COLOR + "; -fx-border-radius: 12px; -fx-padding: 20px; " +
                "-fx-effect: dropshadow(gaussian, rgba(0,0,0,0.04), 8, 0, 0, 3);");
        return card;
    }

    private Button createBackButton(Runnable onBack) {
        Button btn = new Button("← Back");
        String normalStyle = FONT + "-fx-background-color: #FFFFFF; -fx-text-fill: #334155; " +
                "-fx-font-size: 12px; -fx-font-weight: 600; -fx-background-radius: 8px; -fx-border-color: #CBD5E1; " +
                "-fx-border-radius: 8px; -fx-padding: 6px 14px; -fx-cursor: hand;";
        String hoverStyle = FONT + "-fx-background-color: #EEF2FF; -fx-text-fill: " + PRIMARY_COLOR + "; " +
                "-fx-font-size: 12px; -fx-font-weight: 600; -fx-background-radius: 8px; -fx-border-color: #C7D2FE; " +
                "-fx-border-radius: 8px; -fx-padding: 6px 14px; -fx-cursor: hand;";
        btn.setStyle(normalStyle);
        btn.setOnMouseEntered(e -> btn.setStyle(hoverStyle));
        btn.setOnMouseExited(e -> btn.setStyle(normalStyle));
        if (onBack != null) {
            btn.setOnAction(e -> onBack.run());
        }
        return btn;
    }

    private Button createSecondaryButton(String text) {
        Button btn = new Button(text);
        String normalStyle = FONT + "-fx-background-color: #FFFFFF; -fx-text-fill: #334155; " +
                "-fx-font-size: 12px; -fx-font-weight: 600; -fx-background-radius: 8px; -fx-border-color: #CBD5E1; " +
                "-fx-border-radius: 8px; -fx-padding: 8px 16px; -fx-cursor: hand;";
        String hoverStyle = FONT + "-fx-background-color: #F1F5F9; -fx-text-fill: #0F172A; " +
                "-fx-font-size: 12px; -fx-font-weight: 600; -fx-background-radius: 8px; -fx-border-color: #94A3B8; " +
                "-fx-border-radius: 8px; -fx-padding: 8px 16px; -fx-cursor: hand;";
        btn.setStyle(normalStyle);
        btn.setOnMouseEntered(e -> btn.setStyle(hoverStyle));
        btn.setOnMouseExited(e -> btn.setStyle(normalStyle));
        return btn;
    }

    private Label createBadge(String text) {
        Label badge = new Label(text);
        String bg = "#F1F5F9";
        String fg = "#475569";
        String t = text.toLowerCase();

        if (t.contains("active") || t.contains("available") || t.contains("completed") || t.contains("settled")
                || t.contains("credit") || t.contains("ready")) {
            bg = "#DCFCE7";
            fg = "#16A34A";
        } else if (t.contains("pending") || t.contains("review") || t.contains("low stock")) {
            bg = "#FEF3C7";
            fg = "#D97706";
        } else if (t.contains("overdue") || t.contains("out of stock") || t.contains("suspended")
                || t.contains("debit")) {
            bg = "#FEE2E2";
            fg = "#DC2626";
        }

        badge.setStyle(FONT + "-fx-background-color: " + bg + "; -fx-text-fill: " + fg + "; " +
                "-fx-font-size: 11px; -fx-font-weight: bold; -fx-background-radius: 12px; -fx-padding: 3px 10px;");
        return badge;
    }

    private void styleTableView(TableView<?> table) {
        table.setStyle(FONT + "-fx-background-color: white; -fx-background-radius: 8px; " +
                "-fx-border-color: " + BORDER_COLOR + "; -fx-border-radius: 8px; -fx-padding: 0;");
        table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);
    }
}
